# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vagrant/cmpt276-projects/assign1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vagrant/cmpt276-projects/assign1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/cmpt276-projects/assign1/CMakeFiles /home/vagrant/cmpt276-projects/assign1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/cmpt276-projects/assign1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named authserver

# Build rule for target.
authserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 authserver
.PHONY : authserver

# fast build rule for target.
authserver/fast:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/build
.PHONY : authserver/fast

#=============================================================================
# Target rules for targets named basicserver

# Build rule for target.
basicserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basicserver
.PHONY : basicserver

# fast build rule for target.
basicserver/fast:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/build
.PHONY : basicserver/fast

#=============================================================================
# Target rules for targets named pushserver

# Build rule for target.
pushserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pushserver
.PHONY : pushserver

# fast build rule for target.
pushserver/fast:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/build
.PHONY : pushserver/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

#=============================================================================
# Target rules for targets named userserver

# Build rule for target.
userserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 userserver
.PHONY : userserver

# fast build rule for target.
userserver/fast:
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/build
.PHONY : userserver/fast

AuthServer.o: AuthServer.cpp.o
.PHONY : AuthServer.o

# target to build an object file
AuthServer.cpp.o:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/AuthServer.cpp.o
.PHONY : AuthServer.cpp.o

AuthServer.i: AuthServer.cpp.i
.PHONY : AuthServer.i

# target to preprocess a source file
AuthServer.cpp.i:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/AuthServer.cpp.i
.PHONY : AuthServer.cpp.i

AuthServer.s: AuthServer.cpp.s
.PHONY : AuthServer.s

# target to generate assembly for a file
AuthServer.cpp.s:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/AuthServer.cpp.s
.PHONY : AuthServer.cpp.s

BasicServer.o: BasicServer.cpp.o
.PHONY : BasicServer.o

# target to build an object file
BasicServer.cpp.o:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/BasicServer.cpp.o
.PHONY : BasicServer.cpp.o

BasicServer.i: BasicServer.cpp.i
.PHONY : BasicServer.i

# target to preprocess a source file
BasicServer.cpp.i:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/BasicServer.cpp.i
.PHONY : BasicServer.cpp.i

BasicServer.s: BasicServer.cpp.s
.PHONY : BasicServer.s

# target to generate assembly for a file
BasicServer.cpp.s:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/BasicServer.cpp.s
.PHONY : BasicServer.cpp.s

ClientUtils.o: ClientUtils.cpp.o
.PHONY : ClientUtils.o

# target to build an object file
ClientUtils.cpp.o:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/ClientUtils.cpp.o
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/ClientUtils.cpp.o
.PHONY : ClientUtils.cpp.o

ClientUtils.i: ClientUtils.cpp.i
.PHONY : ClientUtils.i

# target to preprocess a source file
ClientUtils.cpp.i:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/ClientUtils.cpp.i
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/ClientUtils.cpp.i
.PHONY : ClientUtils.cpp.i

ClientUtils.s: ClientUtils.cpp.s
.PHONY : ClientUtils.s

# target to generate assembly for a file
ClientUtils.cpp.s:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/ClientUtils.cpp.s
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/ClientUtils.cpp.s
.PHONY : ClientUtils.cpp.s

PushServer.o: PushServer.cpp.o
.PHONY : PushServer.o

# target to build an object file
PushServer.cpp.o:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/PushServer.cpp.o
.PHONY : PushServer.cpp.o

PushServer.i: PushServer.cpp.i
.PHONY : PushServer.i

# target to preprocess a source file
PushServer.cpp.i:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/PushServer.cpp.i
.PHONY : PushServer.cpp.i

PushServer.s: PushServer.cpp.s
.PHONY : PushServer.s

# target to generate assembly for a file
PushServer.cpp.s:
	$(MAKE) -f CMakeFiles/pushserver.dir/build.make CMakeFiles/pushserver.dir/PushServer.cpp.s
.PHONY : PushServer.cpp.s

ServerUtils.o: ServerUtils.cpp.o
.PHONY : ServerUtils.o

# target to build an object file
ServerUtils.cpp.o:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/ServerUtils.cpp.o
.PHONY : ServerUtils.cpp.o

ServerUtils.i: ServerUtils.cpp.i
.PHONY : ServerUtils.i

# target to preprocess a source file
ServerUtils.cpp.i:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/ServerUtils.cpp.i
.PHONY : ServerUtils.cpp.i

ServerUtils.s: ServerUtils.cpp.s
.PHONY : ServerUtils.s

# target to generate assembly for a file
ServerUtils.cpp.s:
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/ServerUtils.cpp.s
.PHONY : ServerUtils.cpp.s

TableCache.o: TableCache.cpp.o
.PHONY : TableCache.o

# target to build an object file
TableCache.cpp.o:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/TableCache.cpp.o
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/TableCache.cpp.o
.PHONY : TableCache.cpp.o

TableCache.i: TableCache.cpp.i
.PHONY : TableCache.i

# target to preprocess a source file
TableCache.cpp.i:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/TableCache.cpp.i
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/TableCache.cpp.i
.PHONY : TableCache.cpp.i

TableCache.s: TableCache.cpp.s
.PHONY : TableCache.s

# target to generate assembly for a file
TableCache.cpp.s:
	$(MAKE) -f CMakeFiles/authserver.dir/build.make CMakeFiles/authserver.dir/TableCache.cpp.s
	$(MAKE) -f CMakeFiles/basicserver.dir/build.make CMakeFiles/basicserver.dir/TableCache.cpp.s
.PHONY : TableCache.cpp.s

UserServer.o: UserServer.cpp.o
.PHONY : UserServer.o

# target to build an object file
UserServer.cpp.o:
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/UserServer.cpp.o
.PHONY : UserServer.cpp.o

UserServer.i: UserServer.cpp.i
.PHONY : UserServer.i

# target to preprocess a source file
UserServer.cpp.i:
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/UserServer.cpp.i
.PHONY : UserServer.cpp.i

UserServer.s: UserServer.cpp.s
.PHONY : UserServer.s

# target to generate assembly for a file
UserServer.cpp.s:
	$(MAKE) -f CMakeFiles/userserver.dir/build.make CMakeFiles/userserver.dir/UserServer.cpp.s
.PHONY : UserServer.cpp.s

tester.o: tester.cpp.o
.PHONY : tester.o

# target to build an object file
tester.cpp.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tester.cpp.o
.PHONY : tester.cpp.o

tester.i: tester.cpp.i
.PHONY : tester.i

# target to preprocess a source file
tester.cpp.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tester.cpp.i
.PHONY : tester.cpp.i

tester.s: tester.cpp.s
.PHONY : tester.s

# target to generate assembly for a file
tester.cpp.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tester.cpp.s
.PHONY : tester.cpp.s

testmain.o: testmain.cpp.o
.PHONY : testmain.o

# target to build an object file
testmain.cpp.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/testmain.cpp.o
.PHONY : testmain.cpp.o

testmain.i: testmain.cpp.i
.PHONY : testmain.i

# target to preprocess a source file
testmain.cpp.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/testmain.cpp.i
.PHONY : testmain.cpp.i

testmain.s: testmain.cpp.s
.PHONY : testmain.s

# target to generate assembly for a file
testmain.cpp.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/testmain.cpp.s
.PHONY : testmain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... authserver"
	@echo "... basicserver"
	@echo "... edit_cache"
	@echo "... pushserver"
	@echo "... rebuild_cache"
	@echo "... tester"
	@echo "... userserver"
	@echo "... AuthServer.o"
	@echo "... AuthServer.i"
	@echo "... AuthServer.s"
	@echo "... BasicServer.o"
	@echo "... BasicServer.i"
	@echo "... BasicServer.s"
	@echo "... ClientUtils.o"
	@echo "... ClientUtils.i"
	@echo "... ClientUtils.s"
	@echo "... PushServer.o"
	@echo "... PushServer.i"
	@echo "... PushServer.s"
	@echo "... ServerUtils.o"
	@echo "... ServerUtils.i"
	@echo "... ServerUtils.s"
	@echo "... TableCache.o"
	@echo "... TableCache.i"
	@echo "... TableCache.s"
	@echo "... UserServer.o"
	@echo "... UserServer.i"
	@echo "... UserServer.s"
	@echo "... tester.o"
	@echo "... tester.i"
	@echo "... tester.s"
	@echo "... testmain.o"
	@echo "... testmain.i"
	@echo "... testmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

